create table if not exists public.chats (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    message text not null,
    response text not null,
    timestamp timestamptz not null default now()
);

create index if not exists chats_user_timestamp_idx
    on public.chats (user_id, timestamp desc);

alter table public.chats enable row level security;

drop policy if exists "Users can read their own chats" on public.chats;
create policy "Users can read their own chats"
    on public.chats for select
    to authenticated
    using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own chats" on public.chats;
create policy "Users can insert their own chats"
    on public.chats for insert
    to authenticated
    with check ((select auth.uid()) = user_id);
